In [2]:
import pandas as pd
import numpy as np

In [ ]:
csv_path = "../outputs/module1_results.csv"

In [ ]:
df = pd.read_csv(csv_path)

In [5]:
df

image_name  vehicle_count  Pedestrian_count congestion
0    7d06fefd-f7be05a6.jpg              9                 0        LOW
1    7d128593-0ccfea4c.jpg              3                 0        LOW
2    7d15b18b-1e0d6e3f.jpg              6                 0        LOW
3    7d209219-ccdc1a09.jpg              5                 0        LOW
4    7d22891c-224788c0.jpg              3                 0        LOW
..                     ...            ...               ...        ...
995  abc6b442-311adbdf.jpg              2                 0        LOW
996  abf6f644-ade3cfa2.jpg              5                 0        LOW
997  abfbfcb1-0e220001.jpg             17                 0     Medium
998  ac033a32-493865fc.jpg             10                 1     Medium
999  ac45a2b9-df30e99b.jpg             10                 3     Medium

[1000 rows x 4 columns]

In [ ]:
df = df.reset_index(drop=True)

In [7]:
df

image_name  vehicle_count  Pedestrian_count congestion
0    7d06fefd-f7be05a6.jpg              9                 0        LOW
1    7d128593-0ccfea4c.jpg              3                 0        LOW
2    7d15b18b-1e0d6e3f.jpg              6                 0        LOW
3    7d209219-ccdc1a09.jpg              5                 0        LOW
4    7d22891c-224788c0.jpg              3                 0        LOW
..                     ...            ...               ...        ...
995  abc6b442-311adbdf.jpg              2                 0        LOW
996  abf6f644-ade3cfa2.jpg              5                 0        LOW
997  abfbfcb1-0e220001.jpg             17                 0     Medium
998  ac033a32-493865fc.jpg             10                 1     Medium
999  ac45a2b9-df30e99b.jpg             10                 3     Medium

[1000 rows x 4 columns]

In [ ]:
cong_map = {"LOW": 0, "Medium": 1, "High": 2}

congestion_labels = df["congestion"].map(cong_map).values

In [ ]:
vehicle_counts = df["vehicle_count"].values
sequence_length = 5

Features = df[["vehicle_count", "Pedestrian_count"]].values

In [ ]:
X = []
Y = []

for i in range(len(Features) - sequence_length):
    seq = Features[i : i + sequence_length]
    label = congestion_labels[i + sequence_length]
    X.append(seq)
    Y.append(label)

In [ ]:
X = np.array(X)
X

array([[[ 9,  0],
        [ 3,  0],
        [ 6,  0],
        [ 5,  0],
        [ 3,  0]],

       [[ 3,  0],
        [ 6,  0],
        [ 5,  0],
        [ 3,  0],
        [ 7,  0]],

       [[ 6,  0],
        [ 5,  0],
        [ 3,  0],
        [ 7,  0],
        [ 0,  0]],

       ...,

       [[ 0,  0],
        [ 5,  0],
        [ 0,  0],
        [ 2,  0],
        [ 5,  0]],

       [[ 5,  0],
        [ 0,  0],
        [ 2,  0],
        [ 5,  0],
        [17,  0]],

       [[ 0,  0],
        [ 2,  0],
        [ 5,  0],
        [17,  0],
        [10,  1]]], shape=(995, 5, 2))

In [ ]:
Y = np.array(Y)

In [13]:
Y

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,

In [14]:
X = X.astype(np.float32)
X

array([[[ 9.,  0.],
        [ 3.,  0.],
        [ 6.,  0.],
        [ 5.,  0.],
        [ 3.,  0.]],

       [[ 3.,  0.],
        [ 6.,  0.],
        [ 5.,  0.],
        [ 3.,  0.],
        [ 7.,  0.]],

       [[ 6.,  0.],
        [ 5.,  0.],
        [ 3.,  0.],
        [ 7.,  0.],
        [ 0.,  0.]],

       ...,

       [[ 0.,  0.],
        [ 5.,  0.],
        [ 0.,  0.],
        [ 2.,  0.],
        [ 5.,  0.]],

       [[ 5.,  0.],
        [ 0.,  0.],
        [ 2.,  0.],
        [ 5.,  0.],
        [17.,  0.]],

       [[ 0.,  0.],
        [ 2.,  0.],
        [ 5.,  0.],
        [17.,  0.],
        [10.,  1.]]], shape=(995, 5, 2), dtype=float32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()

model.add(LSTM(units=64, return_sequences=False, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.3))
model.add(Dense(3, activation="softmax"))
model.compile(
    optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
)

c:\Users\DELL\Documents\DL CCP\my_env\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
c:\Users\DELL\Documents\DL CCP\my_env\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, Y, test_size=0.2, random_state=42)

history = model.fit(
    X_train, y_train, epochs=15, batch_size=32, validation_data=(X_val, y_val)
)

Epoch 1/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.6595 - loss: 0.7952 - val_accuracy: 0.7437 - val_loss: 0.6120
Epoch 2/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7638 - loss: 0.5837 - val_accuracy: 0.7437 - val_loss: 0.5728
Epoch 3/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7588 - loss: 0.5611 - val_accuracy: 0.7437 - val_loss: 0.5692
Epoch 4/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7626 - loss: 0.5639 - val_accuracy: 0.7437 - val_loss: 0.5624
Epoch 5/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7588 - loss: 0.5666 - val_accuracy: 0.7437 - val_loss: 0.5617
Epoch 6/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7613 - loss: 0.5522 - val_accuracy: 0.7437 - val_loss: 0.5593
Epoch 7/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7601 - loss: 0.5573 - val_accuracy: 0.7437 - val_loss: 0.5576
Epoch 8/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7588 - loss: 0.5531 - val_accuracy: 0.7437 - val_

In [17]:
model.save("Traffic_Model_LSTM.h5")